version: "2.34.0"
services:
  api:
    image: tonygao777/fastapi
    ports:
      - "80:8000"
    env_file:
      - ./backend/.env

  frontend:
    image: front
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://api:8000
    depends_on:
      - api
