"""create user_engagment table

Revision ID: bbba96f1f3aa
Revises: 
Create Date: 2025-03-16 16:15:18.757377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbba96f1f3aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_engagement',
    sa.Column('total_time_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_pauses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('correct_answers', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('session_started', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('video_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_engagement')
    # ### end Alembic commands ###
